### PR TITLE
Add temperature flow conditions

### PR DESCRIPTION
**Pull request by jenssegers**
This PR adds temperature flow conditions. This allows for flow logic like this:

image

Tested on my local Homey with logs 👍

### CODE REVIEW

**Comment by jenssegers** [comment]
@tomaszkoperski What do you think?

**Comment by tomaszkoperski** [comment]
@jenssegers looks good, big thanks! Will release that to Homey store over the weekend.

**Comment by jenssegers** [comment]
@tomaszkoperski Did you end up pushing this to the Homey store? Currently trying to figure out how I can replace my custom install with the store version.

**Comment by tomaszkoperski** [comment]
@jenssegers sorry for the delay, I didn't have much time last week. I've pushed it just now under v1.3.0. Should be available in the test: https://homey.app/a/com.zehnder-systems.comfoconnect/test/ immediately and via the release channel after Homey's certification (usually ~1 day).

**Pull request merged**
